config/routes.rb
Rails.application.routes.draw do
	get 					'login', 						to: 'sessions#new'
	post 				'login',						to: 'sessions#create'
	delete 				'logout', 					to: 'sessions#destroy'
	root                                       				'static_pages#index'
	get 					'contact',                          to: 'static_pages#contact'
	get					'fields',                           to: 'fields#index'
	get 					'doctors',                          to: 'doctors#index'
	get 					'users',                            to: 'users#index'
	resources :gibes, :fields, :doctors, :users
	get 					'doctor_login',				to: 'sessions#new_doctor'
	post 				'doctor_login',				to: 'sessions#create_doctor'
	delete				'doctor_logout', 				to: 'sessions#destroy_doctor'


end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save {self.email = email.downcase}
	validates :name, presence: true
	validates :contact, presence: true
	validates :address, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:  true,
		format: {with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
	
	has_secure_password
	validates :password_digest, presence: true, length: {minimum: 6}

	# Returns the hash digest of the given string.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
					BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest , nil)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper
	before_action :check_logged_in
#			before_action :check_user_status, only: [:destroy]
	before_action :check_doctor_status
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user, only:  [:destroy]



	def index
		#@users = User.all
		@users = User.order(:name).page(params[:page]).per(15)
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params_user)
		if @user.save
			flash[:success] = "New user added"
			redirect_to users_url
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params_user)
			flash[:success] = "User profile updated"
			redirect_to users_url
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).delete
		flash[:success]  = "User successfully deleted"
		redirect_to users_url
	end

	private

		def params_user
			params.require(:user).permit(:name, :email, :contact, :address, :password, :password_confirmation )
		end

		def check_user_status
			if  logged_in?
				redirect_to root_url
			end
		end

		def check_doctor_status
			if logged_in_doctor?
				redirect_to root_url
			end
		end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
	<%= user.name %>
	<span class="float-sm-right" style= "clear: both;" >
	<%= link_to '<i class="material-icons", style="font-size: 24px; color: #2f4858">perm_contact_calendar</i>'.html_safe, user, style: "padding-right: 10px", target: "_self", title:"View Doctor" %>
	<% if current_user.admin? %>
			<%= link_to '<i class="material-icons", style="font-size: 24px; color: #da5530">edit</i>'.html_safe, edit_user_path(user), style: "padding-left: 10px; padding-right: 10px", target: "_self", title:"Edit Doctor" %>
			<%= link_to '<i class="material-icons", style="font-size: 24px; color: #ff0000">delete_forever</i>'.html_safe, user, method: :delete, data: {confirm: "Are you sure?"}, target: "_self", title:"Delete Doctor" %>
	<% end  %>
	</span>
</li>

app/views/users/edit.html.erb
<div class="col-md-10">
	<div class="card">
		<div class="card-header card-header-primary">
			<h4 class="card-title">Edit User Profile</h4>
			<p class="card-category">Fill-out completely</p>
		</div>
		<div class="card-body">
			<%= form_for (@user) do |f| %>
				<div clas="row">
					<div class="col-md-12">
						<%= render 'shared/error_messages', object: f.object %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 form-group">
						<%= f.label :name, class: "bmd-label-floating"  %>
						<%= f.text_field :name, class: "form-control" %>
					</div>
					<div class="col-md-6 form-group">
						<%= f.label :email, class: "bmd-label-floating" %>
						<%= f.email_field :email, class: "form-control" %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 form-group">
						<%= f.label :contact, class: "bmd-label-floating" %>
						<%= f.text_field :contact, class: "form-control" %>
					</div>
					<div class="col-md-6 form-group">
						<%= f.label :address, class: "bmd-label-floating" %>
						<%= f.text_field :address, class: "form-control" %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 form-group">
						<%= f.label :password, class: "bmd-label-floating" %>
						<%= f.password_field :password, class: "form-control" %>
					</div>
					<div class="col-md-6 form-group">
						<%= f.label :password_confirmation, class: "bmd-label-floating" %>
						<%= f.password_field :password_confirmation, class:  "form-control" %>
					</div>
				</div>
				<%= f.submit "Update Account", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="col-md-10">
      <%= link_to "Add User", new_user_path, class: "btn btn-primary" %>
      <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title">List of Users</h4>
                <p class="card-category">There are <%= pluralize(User.count, "User") %></p>
              </div>
              <div class="card-body">
                    <div class="row">
                          <div class="col-md-12">
                                <ul class="horizontal-display">
                                      <%= render @users %>
                                </ul>
                                <div class="d-flex justify-content-center">
                                      <%=paginate @users %>
                                </div>
                          </div>
                    </div>
              </div>

      </div>
</div>

app/views/users/new.html.erb
<div class="col-md-10">
      <div class="card">
            <div class="card-header card-header-primary">
                  <h4 class="card-title">User Profile</h4>
                  <p class="card-category">Fill-out completely</p>
            </div>
            <div class="card-body">
                  <%= form_for (@user) do |f| %>
                        <div clas="row">
                              <div class="col-md-12">
                                    <%= render 'shared/error_messages', object: f.object %>
                              </div>
                        </div>
                        <div class="row">
                              <div class="col-md-6 form-group">
                                    <%= f.label :name, class: "bmd-label-floating"  %>
                                    <%= f.text_field :name, class: "form-control" %>
                              </div>
                              <div class="col-md-6 form-group">
                                    <%= f.label :email, class: "bmd-label-floating" %>
                                    <%= f.email_field :email, class: "form-control" %>
                              </div>
                        </div>
                        <div class="row">
                              <div class="col-md-6 form-group">
                                    <%= f.label :contact, class: "bmd-label-floating" %>
                                    <%= f.text_field :contact, class: "form-control" %>
                              </div>
                              <div class="col-md-6 form-group">
                                    <%= f.label :address, class: "bmd-label-floating" %>
                                    <%= f.text_field :address, class: "form-control" %>
                              </div>
                        </div>
                        <div class="row">
                              <div class="col-md-6 form-group">
                                    <%= f.label :password, class: "bmd-label-floating" %>
                                    <%= f.password_field :password, class: "form-control" %>
                              </div>
                              <div class="col-md-6 form-group">
                                    <%= f.label :password_confirmation, class: "bmd-label-floating" %>
                                    <%= f.password_field :password_confirmation, class:  "form-control" %>
                              </div>
                        </div>
                        <%= f.submit "Create Account", class: "btn btn-primary" %>
                  <% end %>
            </div>
      </div>
</div>

app/views/users/show.html.erb
<div class="col-md-10">
	<div class="card">
		<div class="card-header card-header-primary">
			<h4 class="card-title">User's profile</h4>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-md-2">
					<%= gravatar_for @user %>
				</div>
				<div class="col-md-10">
					<table class="table">
						<tbody>
						<tr scope="row">
							<td colspan="2"><h3><%= @user.name %></h3></td>
						</tr>
						<tr scope="row">
							<td>Email</td>
							<td><%= @user.email %></td>
						</tr>
						<tr scope="row">
							<td>Contact</td>
							<td><%= @user.contact %></td>
						</tr>
						<tr scope="row">
							<td>Address</td>
							<td><%= @user.address %></td>
						</tr>
						</tbody>
					</table>

				</div>

			</div>
			<div class="row">
				<div class="col-md-10 offset-2">
					<% if correct_user? || current_user.admin? %>
						<%= link_to "Edit", edit_user_path(@user), class: "btn btn-primary" %>
					<% end %>
					<% if current_user.admin? %>
						<%= link_to "Delete", @user, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"  %>
					<% end %>

				</div>
			</div>

		</div>
	</div>
</div>