config/routes.rb
Rails.application.routes.draw do
	get 					'login', 						to: 'sessions#new'
	post 				'login',						to: 'sessions#create'
	delete 				'logout', 					to: 'sessions#destroy'
	root                                       				'static_pages#index'
	get 					'contact',                          to: 'static_pages#contact'
	get					'fields',                           to: 'fields#index'
	get 					'doctors',                          to: 'doctors#index'
	get 					'users',                            to: 'users#index'
	resources :gibes, :fields, :doctors, :users
	get 					'doctor_login',				to: 'sessions#new_doctor'
	post 				'doctor_login',				to: 'sessions#create_doctor'
	delete				'doctor_logout', 				to: 'sessions#destroy_doctor'


end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>


  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>


<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <nav class="float-left">
      <ul>
        <li>
          <a href="https://www.creative-tim.com">
            Creative Tim
          </a>
        </li>
        <li>
          <a href="https://creative-tim.com/presentation">
            About Us
          </a>
        </li>
        <li>
          <a href="http://blog.creative-tim.com">
            Blog
          </a>
        </li>
        <li>
          <a href="https://www.creative-tim.com/license">
            Licenses
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright float-right">
      &copy;
      <script>
          document.write(new Date().getFullYear())
      </script>, made with <i class="material-icons">favorite</i> by
      <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
	<!--
	  Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

	  Tip 2: you can also add an image using data-image tag
   -->
	<div class="logo"><a href="http://www.creative-tim.com" class="simple-text logo-normal">
		Creative Tim
	</a></div>
	<div class="sidebar-wrapper">
		<ul class="nav">
			<li class="nav-item active  ">
				<%= link_to '<i class="material-icons">dashboard</i><p>Dashboard</p>'.html_safe, root_url, class: 'nav-link', target: "_self" %>
			</li>
			<li class="nav-item ">
				<%= link_to '<i class="material-icons">person</i><p>User Profile</p>'.html_safe, current_user, class: 'nav-link',  target: "_self"%>
			</li>
			<% unless logged_in_doctor? %>
				<li class="nav-item ">
					<%= link_to '<i class="material-icons">group_add</i><p>Users</p>'.html_safe, users_url, class: 'nav-link', target:  "_self" %>
				</li>
				<li class="nav-item">
					<%= link_to  '<i class="material-icons">library_add</i><p>Specialty</p>'.html_safe, fields_url, class: 'nav-link', target: "_self"%>
				</li>
				<li class="nav-item">
					<%= link_to '<i class="material-icons">assignment_ind</i><p>Doctor</p>'.html_safe, doctors_path, class: 'nav-link', target: "_self" %>
				</li>
			<% end %>

		</ul>
	</div>
</div>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
	<div class="container-fluid">

		<button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
			<span class="sr-only">Toggle navigation</span>
			<span class="navbar-toggler-icon icon-bar"></span>
			<span class="navbar-toggler-icon icon-bar"></span>
			<span class="navbar-toggler-icon icon-bar"></span>
		</button>
		<div class="collapse navbar-collapse justify-content-end">
			<form class="navbar-form">
				<div class="input-group no-border">
					<input type="text" value="" class="form-control" placeholder="Search...">
					<button type="submit" class="btn btn-white btn-round btn-just-icon">
						<i class="material-icons">search</i>
						<div class="ripple-container"></div>
					</button>
				</div>
			</form>
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="javascript:;">
						<i class="material-icons">dashboard</i>
						<p class="d-lg-none d-md-block">
							Stats
						</p>
					</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="material-icons">notifications</i>
						<span class="notification">5</span>
						<p class="d-lg-none d-md-block">
							Some Actions
						</p>
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
						<a class="dropdown-item" href="#">Mike John responded to your email</a>
						<a class="dropdown-item" href="#">You have 5 new tasks</a>
						<a class="dropdown-item" href="#">You're now friend with Andrew</a>
						<a class="dropdown-item" href="#">Another Notification</a>
						<a class="dropdown-item" href="#">Another One</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="material-icons">person</i>
						<p class="d-lg-none d-md-block">
							Account
						</p>
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
						<%= link_to "Profile", logged_in? ? current_user : current_doctor, class: "dropdown-item" %>
						<%= link_to "Settings", logged_in? ? edit_user_path(current_user) : edit_doctor_path(current_doctor), class: "dropdown-item" %>
						<div class="dropdown-divider"></div>
						<%= link_to "Log out", logged_in? ? logout_path : doctor_logout_path, method: :delete, class: "dropdown-item" %>
					</div>
				</li>
			</ul>
		</div>
	</div>
</nav>
<!-- End Navbar -->