config/routes.rb
Rails.application.routes.draw do
	get 					'login', 						to: 'sessions#new'
	post 				'login',						to: 'sessions#create'
	delete 				'logout', 					to: 'sessions#destroy'
	root                                       				'static_pages#index'
	get 					'contact',                          to: 'static_pages#contact'
	get					'fields',                           to: 'fields#index'
	get 					'doctors',                          to: 'doctors#index'
	get 					'users',                            to: 'users#index'
	resources :gibes, :fields, :doctors, :users
	get 					'doctor_login',				to: 'sessions#new_doctor'
	post 				'doctor_login',				to: 'sessions#create_doctor'
	delete				'doctor_logout', 				to: 'sessions#destroy_doctor'


end

app/models/field.rb
class Field < ApplicationRecord
  has_many :doctors, dependent: :destroy
  validates :area, length: {maximum: 40}, presence: true
  default_scope -> {order(area: :asc)}
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
	before_action :check_logged_in
	before_action :correct_user, only: [:edit, :update]
	before_action :check_doctor_status


	def index
		@fields = Field.all
	end

	def new
		@field = Field.new
	end

	def show
		@field = Field.find(params[:id])
		#@doctors  = @field.doctors.all
	end

	def create
		@field = Field.new(params_field)
		if @field.save
			flash[:success] = 'Field added'
			redirect_to fields_url
		else
			flash.now[:danger] = 'Error in saving'
			render 'new'
		end
	end

	def edit
		@field = Field.find(params[:id])
	end

	def update
		@field = Field.find(params[:id])
		if @field.update_attributes(params_field)
			flash[:success] = 'Field Updated'
			redirect_to fields_url
		else
			flash.now[:danger] = 'Error in saving'
			render 'edit'
		end
	end

	def destroy
		Field.find(params[:id]).destroy
		#@field.delete
		flash[:success] = 'Field deleted'
		redirect_to fields_url
	end

	private

		def params_field
			params.require(:field).permit(:area)

		end

		def check_doctor_status
			if logged_in_doctor?
				redirect_to root_url
			end
		end


end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_doctor.html.erb
<li>
	<%= doctor.name %>
	<span class="float-sm-right" style= "clear: both;" >
		<%= link_to '<i class="material-icons", style="font-size: 24px; color: #2f4858">perm_contact_calendar</i>'.html_safe, doctor, style: "padding-right: 10px", target: "_self", title:"View Doctor" %>
		<% if current_user.admin? %>
			<%= link_to '<i class="material-icons", style="font-size: 24px; color: #da5530">edit</i>'.html_safe, edit_doctor_path(doctor), style: "padding-left: 10px; padding-right: 10px", target: "_self", title:"Edit Doctor" %>
			<%= link_to '<i class="material-icons", style="font-size: 24px; color: #ff0000">delete_forever</i>'.html_safe, doctor, method: :delete, data: {confirm: "Are you sure?"}, target: "_self", title:"Delete Doctor" %>
		<% end %>
	</span>
</li>

app/views/fields/_field.html.erb
<li>
	<%= field.area %>
	<span class="float-sm-right" style= "clear: both;" >
	<%= link_to '<i class="material-icons", style="font-size: 24px; color: #2f4858">perm_contact_calendar</i>'.html_safe, field , style: "padding-right: 10px", target: "_self", title:"View Doctor" %>
	<% if current_user.admin? %>
		<%= link_to '<i class="material-icons", style="font-size: 24px; color: #da5530">edit</i>'.html_safe, edit_field_path(field), style: "padding-left: 10px; padding-right: 10px", target: "_self", title:"Edit Doctor" %>
		<%= link_to '<i class="material-icons", style="font-size: 24px; color: #ff0000">delete_forever</i>'.html_safe, field, method: :delete, data: {confirm: "Are you sure?"}, target: "_self", title:"Delete Doctor" %>
	<% end %>
	</span>
</li>

app/views/fields/edit.html.erb
<div class="col-md-8">
  <div class="card">
    <div class="card-header card-header-primary">
      <h4 class="card-title">Specialty</h4>
      <p class="card-category">&nbsp;</p>

    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-8">
          <%= form_for(@field) do |f| %>
            <%= render "shared/error_messages", object: f.object %>
            <div class="form-group">
              <%= f.label :area, "Field Area", class: "bmd-label-floating" %>
              <%= f.text_field :area, class: "form-control" %>
            </div>

            </div><!-- col-md-8 -->
            <div class="col-md-4">
              <%= f.submit "Save", class: "btn btn-primary btn-block" %>
            </div><!-- col-md-4-->
          <%  end %>
          </div><!-- row -->
    </div><!-- card-body -->
  </div><!-- card -->
</div><!-- col-md-8 -->

app/views/fields/index.html.erb
<div class="col-md-10">
	<%= link_to "Add Specialty", new_field_path, class: "btn btn-primary", target: "_self" %>
	<div class="card">
		<div class="card-header card-header-primary">
			<h4 class="card-title">Specialty</h4>
			<p class="card-category">&nbsp;</p>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-md-12">
					<ul  class="horizontal-display">
						<%= render @fields %>
					</ul>
				</div>
			</div>

		</div>
	</div><!-- card -->
</div><!-- col-md-10 -->

app/views/fields/new.html.erb
      <div class="col-md-8">
         <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">Specialty</h4>
            <p class="card-category">&nbsp;</p>

          </div>
          <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                  <%= form_for(@field) do |f| %>
                    <%= render "shared/error_messages", object: f.object %>
                  <div class="form-group">
                    <%= f.label :area, "Field Area", class: "bmd-label-floating" %>
                    <%= f.text_field :area, class: "form-control" %>
                  </div>

                </div><!-- col-md-8 -->
                <div class="col-md-4">
                    <%= f.submit "Save", class: "btn btn-primary btn-block" %>
                </div><!-- col-md-4-->
                  <%  end %>
            </div><!-- row -->
          </div><!-- card-body -->
        </div><!-- card -->
      </div><!-- col-md-8 -->

app/views/fields/show.html.erb
<div class="col-md-10">
      <div class="card">
            <div class="card-header card-header-primary">
                  <h4 class="card-title"><%= @field.area %></h4>
                  <p class="card-category"><h5><%= pluralize(@field.doctors.count, "Doctor")%> found</h5></p>
            </div>
            <div class="card-body">
                  <div class="row">
                        <div class="col-md-12">
                              <% if @field.doctors.any? %>
                                    <ul class="horizontal-display">
                                          <% @field.doctors.each do |doctor| %>
                                                <%= render doctor %>
                                          <% end %>
                                    </ul>
                              <% else %>
                                    <div class="alert alert-warning text-center">
                                          <h2>No doctors available</h2>
                                    </div>
                              <% end %>
                        </div>
                  </div>
          </div>
      </div>

</div>