config/routes.rb
Rails.application.routes.draw do
	get 					'login', 						to: 'sessions#new'
	post 				'login',						to: 'sessions#create'
	delete 				'logout', 					to: 'sessions#destroy'
	root                                       				'static_pages#index'
	get 					'contact',                          to: 'static_pages#contact'
	get					'fields',                           to: 'fields#index'
	get 					'doctors',                          to: 'doctors#index'
	get 					'users',                            to: 'users#index'
	resources :gibes, :fields, :doctors, :users
	get 					'doctor_login',				to: 'sessions#new_doctor'
	post 				'doctor_login',				to: 'sessions#create_doctor'
	delete				'doctor_logout', 				to: 'sessions#destroy_doctor'


end

app/models/gibe.rb
class Gibe < ApplicationRecord
end

app/controllers/gibes_controller.rb
class GibesController < ApplicationController
  before_action :set_gibe, only: [:show, :edit, :update, :destroy]

  # GET /gibes
  # GET /gibes.json
  def index
    @gibes = Gibe.all
  end

  # GET /gibes/1
  # GET /gibes/1.json
  def show
  end

  # GET /gibes/new
  def new
    @gibe = Gibe.new
  end

  # GET /gibes/1/edit
  def edit
  end

  # POST /gibes
  # POST /gibes.json
  def create
    @gibe = Gibe.new(gibe_params)

    respond_to do |format|
      if @gibe.save
        format.html { redirect_to @gibe, notice: 'Gibe was successfully created.' }
        format.json { render :show, status: :created, location: @gibe }
      else
        format.html { render :new }
        format.json { render json: @gibe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gibes/1
  # PATCH/PUT /gibes/1.json
  def update
    respond_to do |format|
      if @gibe.update(gibe_params)
        format.html { redirect_to @gibe, notice: 'Gibe was successfully updated.' }
        format.json { render :show, status: :ok, location: @gibe }
      else
        format.html { render :edit }
        format.json { render json: @gibe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gibes/1
  # DELETE /gibes/1.json
  def destroy
    @gibe.destroy
    respond_to do |format|
      format.html { redirect_to gibes_url, notice: 'Gibe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gibe
      @gibe = Gibe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gibe_params
      params.require(:gibe).permit(:name, :address)
    end
end

app/helpers/gibes_helper.rb
module GibesHelper
end

app/views/gibes/_form.html.erb
<%= form_with(model: gibe, local: true) do |form| %>
  <% if gibe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gibe.errors.count, "error") %> prohibited this gibe from being saved:</h2>

      <ul>
        <% gibe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gibes/edit.html.erb
<h1>Editing Gibe</h1>

<%= render 'form', gibe: @gibe %>

<%= link_to 'Show', @gibe %> |
<%= link_to 'Back', gibes_path %>

app/views/gibes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gibes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gibes.each do |gibe| %>
      <tr>
        <td><%= gibe.name %></td>
        <td><%= gibe.address %></td>
        <td><%= link_to 'Show', gibe %></td>
        <td><%= link_to 'Edit', edit_gibe_path(gibe) %></td>
        <td><%= link_to 'Destroy', gibe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gibe', new_gibe_path %>

app/views/gibes/new.html.erb
<h1>New Gibe</h1>

<%= render 'form', gibe: @gibe %>

<%= link_to 'Back', gibes_path %>

app/views/gibes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gibe.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @gibe.address %>
</p>

<%= link_to 'Edit', edit_gibe_path(@gibe) %> |
<%= link_to 'Back', gibes_path %>